// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestTask.DbSettings;

#nullable disable

namespace TestTask.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260303095100_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TestTask.DbSettings.TaxiTrip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DOLocationID")
                        .HasColumnType("int");

                    b.Property<DateTime>("DropoffDatetimeUTC")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("FareAmount")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int?>("PULocationID")
                        .HasColumnType("int");

                    b.Property<int?>("PassengerCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("PickupDatetimeUTC")
                        .HasColumnType("datetime2");

                    b.Property<string>("StoreAndFwdFlag")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<decimal?>("TipAmount")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal?>("TripDistance")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int?>("TripDurationSeconds")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("int")
                        .HasComputedColumnSql("DATEDIFF(SECOND, PickupDatetimeUTC, DropoffDatetimeUTC)", true);

                    b.HasKey("Id");

                    b.HasIndex("PULocationID")
                        .HasDatabaseName("IX_TaxiTrips_PULocationID_Includes");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("PULocationID"), new[] { "TipAmount" });

                    b.HasIndex("TripDistance")
                        .IsDescending()
                        .HasDatabaseName("IX_TaxiTrips_TripDistance");

                    b.HasIndex("TripDurationSeconds")
                        .IsDescending()
                        .HasDatabaseName("IX_TaxiTrips_TripDuration");

                    b.ToTable("TaxiTrips", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
